# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'croppp.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 79, 761, 481))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(r"pic.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 0, 781, 571))
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 761, 31))
        self.label_2.setStyleSheet("background-color: rgb(239, 255, 156);\n"
"font: 75  20pt \"Script MT Bold\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 761, 401))
        self.label_3.setStyleSheet(r"border-image: url(:/img/paddy-rice-and-rice-seed-in-farm-organic-rice-field-and-agriculture-free-photo.jpg);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(30, 80, 271, 481))
        self.label_4.setStyleSheet("background-color:rgb(0,0,0,75);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(60, 190, 221, 171))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(350, 260, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(239, 255, 156);\n"
"\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(350, 310, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(239, 255, 156);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(350, 360, 301, 31))
        self.label_8.setStyleSheet("background-color: rgb(239, 255, 156);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(350, 110, 301, 31))
        self.label_9.setStyleSheet("background-color: rgb(239, 255, 156);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(350, 160, 301, 31))
        self.label_10.setStyleSheet("background-color: rgb(239, 255, 156);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(350, 210, 301, 31))
        self.label_11.setStyleSheet("background-color: rgb(239, 255, 156);")
        self.label_11.setObjectName("label_11")
        self.label_cresult = QtWidgets.QLabel(self.widget)
        self.label_cresult.setGeometry(QtCore.QRect(510, 500, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_cresult.setFont(font)
        self.label_cresult.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0,128,0);")
        self.label_cresult.setObjectName("label_cresult")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_1.setGeometry(QtCore.QRect(650, 110, 91, 31))
        self.lineEdit_1.setText("")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(650, 160, 91, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(650, 210, 91, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(650, 260, 91, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(650, 310, 91, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(650, 360, 91, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setGeometry(QtCore.QRect(350, 410, 301, 31))
        self.label_13.setStyleSheet("background-color: rgb(239, 255, 156);")
        self.label_13.setObjectName("label_13")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setGeometry(QtCore.QRect(650, 410, 91, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(530, 450, 111, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(47, 93, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.pushButton.setObjectName("pushButton")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(10, 40, 761, 41))
        self.label_12.setStyleSheet("background-color: rgb(0, 128, 0);")
        self.label_12.setObjectName("label_12")

        MainWindow.setCentralWidget(self.centralwidget)

        self.pushButton.clicked.connect(self.predict)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def predict(self):
        a=self.lineEdit_1.text()
        b=self.lineEdit_2.text()
        c=self.lineEdit_3.text()
        d=self.lineEdit_4.text()
        e=self.lineEdit_5.text()
        f=self.lineEdit_6.text()
        g=self.lineEdit_7.text()
        import pandas as pd
        import numpy as np
        a=float(a)
        b=float(b)
        c=float(c)
        d=float(d)
        e=float(e)
        f=float(f)
        g=float(g)
        path="C:\\Users\\SANGEETHA T SHENOY\\Desktop\\SMART FARMING\\SmartCrop-Dataset.csv"
        data=pd.read_csv(path)
        data.rename(columns = {'label':'Crop'}, inplace= True)
        inputs=data.drop('Crop',axis=1)
        output=data.Crop
        import sklearn
        from sklearn.linear_model import LogisticRegression
        model=LogisticRegression()
        model.fit(inputs,output)
        res=model.predict([[a,b,c,d,e,f,g]])
        self.label_cresult.setText(str(res))
        acc=model.score(inputs,output)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "                         Intelli Farm : Smart Farming Solutions"))
        self.label_5.setText(_translate("MainWindow", "CROP PREDICTION"))
        self.label_6.setText(_translate("MainWindow", " TEMPERATURE"))
        self.label_7.setText(_translate("MainWindow", "  HUMIDITY"))
        self.label_8.setText(_translate("MainWindow", " pH"))
        self.label_9.setText(_translate("MainWindow", "  NITROGEN"))
        self.label_10.setText(_translate("MainWindow", "  PHOSPHORUS"))
        self.label_11.setText(_translate("MainWindow", "  POTASSIUM"))
        self.label_cresult.setText(_translate("MainWindow", "        RESULT"))
        self.label_13.setText(_translate("MainWindow", "  RAINFALL"))
        self.pushButton.setText(_translate("MainWindow", "PREDICT"))
        self.label_12.setText(_translate("MainWindow", "                                                                      PREDICT THE CROP AND THE FERTILIZER TO BE USED FOR THE BEST YIELD "))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
