from PyQt5 import QtCore, QtGui, QtWidgets
from croppp import Ui_MainWindow
from fertiii import Ui_SecondWindow

class Ui_Dialog(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def open_Window(self):
        self.window1 = QtWidgets.QMainWindow()
        self.ui = Ui_SecondWindow()
        self.ui.setupUi(self.window1)
        self.window1.show()
        
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(786, 586)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(10, 10, 781, 611))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(0, 40, 761, 511))
        self.label.setStyleSheet("border-image: url(:/img/paddy-rice-and-rice-seed-in-farm-organic-rice-field-and-agriculture-free-photo.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("pic.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(90, 80, 291, 471))
        self.label_2.setStyleSheet("background-color: rgb(0,0,0,50);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(110, 200, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.pushButton_cprediction = QtWidgets.QPushButton(self.widget, clicked = lambda: self.openWindow())
        self.pushButton_cprediction.setEnabled(True)
        self.pushButton_cprediction.setGeometry(QtCore.QRect(470, 260, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_cprediction.setFont(font)
        self.pushButton_cprediction.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_cprediction.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(239, 255, 156);")
        self.pushButton_cprediction.setObjectName("pushButton_cprediction")
        self.pushButton_fprediction = QtWidgets.QPushButton(self.widget, clicked = lambda: self.open_Window())
        self.pushButton_fprediction.setEnabled(True)
        self.pushButton_fprediction.setGeometry(QtCore.QRect(470, 340, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_fprediction.setFont(font)
        self.pushButton_fprediction.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_fprediction.setStyleSheet("background-color: rgb(239, 255, 156);\n"
"border-radius:5px;")
        self.pushButton_fprediction.setObjectName("pushButton_fprediction")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(-60, 20, 821, 61))
        self.label_4.setStyleSheet("background-color: rgb(0, 128, 0);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setEnabled(True)
        self.label_6.setGeometry(QtCore.QRect(110, 260, 251, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(200, 40, 381, 20))
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setEnabled(True)
        self.label_5.setGeometry(QtCore.QRect(0, 1, 761, 20))
        self.label_5.setStyleSheet("background-color: rgb(239, 255, 156);\n"
"")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "SMART FARMING"))
        self.pushButton_cprediction.setText(_translate("Dialog", "CROP PREDICTION"))
        self.pushButton_fprediction.setText(_translate("Dialog", "FERTILIZER PREDICTION"))
        self.label_6.setText(_translate("Dialog", "By optimizing resources and improving decision-making, it helps farmers increase yields while minimizing environmental impact. Embrace innovatin for a healthier planet and better crops!"))
        self.label_7.setText(_translate("Dialog", "  PREDICT THE CROP AND THE FERTILIZER TO BE USED FOR THE BEST YIELD "))
        self.label_5.setText(_translate("Dialog", "                                                                                                        Intelli Farm : Smart Farming Solutions"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
