# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fertiii.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(800, 556)
        self.centralwidget = QtWidgets.QWidget(SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 80, 761, 450))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(r"pic.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 781, 541))
        self.widget.setObjectName("widget")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 761, 361))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border-image: url(:/img/paddy-rice-and-rice-seed-in-farm-organic-rice-field-and-agriculture-free-photo.jpg);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 761, 31))
        self.label_5.setStyleSheet("background-color: rgb(239, 255, 156);\n"
"font: 75 20pt \"Script MT Bold\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(30, 70, 271, 451))
        self.label_6.setStyleSheet("background-color:rgb(0,0,0,50);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(50, 200, 231, 171))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(340, 140, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(239, 255, 156);\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(340, 340, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(239, 255, 156);\n"
"")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(340, 290, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(239, 255, 156);\n"
"")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(340, 240, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background-color: rgb(239, 255, 156);\n"
"")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(340, 190, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(239, 255, 156);\n"
"")
        self.label_12.setObjectName("label_12")
        self.lineEdit_fphosphorus = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_fphosphorus.setGeometry(QtCore.QRect(640, 240, 91, 31))
        self.lineEdit_fphosphorus.setText("")
        self.lineEdit_fphosphorus.setObjectName("lineEdit_fphosphorus")
        self.lineEdit_fpotassium = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_fpotassium.setGeometry(QtCore.QRect(640, 290, 91, 31))
        self.lineEdit_fpotassium.setText("")
        self.lineEdit_fpotassium.setObjectName("lineEdit_fpotassium")
        self.lineEdit_fph = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_fph.setGeometry(QtCore.QRect(640, 340, 91, 31))
        self.lineEdit_fph.setText("")
        self.lineEdit_fph.setObjectName("lineEdit_fph")
        self.lineEdit_fcrop = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_fcrop.setGeometry(QtCore.QRect(640, 140, 91, 31))
        self.lineEdit_fcrop.setText("")
        self.lineEdit_fcrop.setObjectName("lineEdit_fcrop")
        self.lineEdit_fnitrogen = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_fnitrogen.setGeometry(QtCore.QRect(640, 190, 91, 31))
        self.lineEdit_fnitrogen.setText("")
        self.lineEdit_fnitrogen.setObjectName("lineEdit_fnitrogen")
        self.label_fresult = QtWidgets.QLabel(self.widget)
        self.label_fresult.setGeometry(QtCore.QRect(450, 460, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_fresult.setFont(font)
        self.label_fresult.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0,128,0);")
        self.label_fresult.setObjectName("label_fresult")
        self.pushButton_predict = QtWidgets.QPushButton(self.widget)
        self.pushButton_predict.setGeometry(QtCore.QRect(510, 400, 101, 41))
        self.pushButton_predict.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_predict.setStyleSheet("background-color: rgb(61, 121, 0);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_predict.setObjectName("pushButton_predict")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 30, 761, 41))
        self.label_2.setStyleSheet("background-color:rgb(0,128,0);")
        self.label_2.setObjectName("label_2")
        
        SecondWindow.setCentralWidget(self.centralwidget)
        
        self.pushButton_predict.clicked.connect(self.predict)

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)
    
    def predict(self):
        a=self.lineEdit_fcrop.text()
        b=self.lineEdit_fnitrogen.text()
        c=self.lineEdit_fphosphorus.text()
        d=self.lineEdit_fpotassium.text()
        e=self.lineEdit_fph.text()
        import pandas as pd
        import numpy as np
        a=float(a)
        b=float(b)
        c=float(c)
        d=float(d)
        e=float(e)
        path1="C:\\Users\\SANGEETHA T SHENOY\\Desktop\\SMART FARMING\\fertilizer.csv"
        data1=pd.read_csv(path1)
        import sklearn
        from sklearn.preprocessing import LabelEncoder
        le_Crop=LabelEncoder()
        data1['Crop']=le_Crop.fit_transform(data1['Crop'])
        inputs1=data1.drop('Fertilizer_Name',axis=1)
        output1=data1.Fertilizer_Name
        from sklearn.linear_model import LogisticRegression
        model=LogisticRegression()
        model.fit(inputs1,output1)
        res=model.predict([[a,b,c,d,e]])
        self.label_fresult.setText(str(res))
        acc=model.score(inputs1,output1)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "MainWindow"))
        self.label_5.setText(_translate("SecondWindow", "                         Intelli Farm : Smart Farming Solutions"))
        self.label_7.setText(_translate("SecondWindow", "FERTILIZER PREDICTION"))
        self.label_8.setText(_translate("SecondWindow", "  CROP"))
        self.label_9.setText(_translate("SecondWindow", "  pH"))
        self.label_10.setText(_translate("SecondWindow", "  POTASSIUM"))
        self.label_11.setText(_translate("SecondWindow", "  PHOSPHORUS"))
        self.label_12.setText(_translate("SecondWindow", "  NITROGEN"))
        self.label_fresult.setText(_translate("SecondWindow", "            RESULT"))
        self.pushButton_predict.setText(_translate("SecondWindow", "PREDICT"))
        self.label_2.setText(_translate("SecondWindow", "                                                                      PREDICT THE CROP AND THE FERTILIZER TO BE USED FOR THE BEST YIELD "))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(SecondWindow)
    SecondWindow.show()
    sys.exit(app.exec_())
